In [1]:
import numpy as np
import torch
from torch import nn

In [2]:
print(torch.__version__)

1.2.0


In [3]:
sample_num, feature_num, output_dim = 100, 6, 4

w = np.random.rand(4)
b = np.random.rand(1).item()

x = 10*np.random.rand(sample_num, feature_num)
y = np.random.rand(sample_num,  output_dim)

x = x.astype(np.float32)
y = y.astype(np.float32)

print(f"x shape {x.shape}, y shape {y.shape}")

x shape (100, 6), y shape (100, 4)


In [4]:
# 通过pytorch搭建一个前馈的模型

class feedForwardNet(nn.Module):
    def __init__(self, input_dim, hidden_size, output_dim):
        super(feedForwardNet, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_size)  
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out 

In [5]:
model = feedForwardNet(input_dim=x.shape[1], hidden_size=4, output_dim=y.shape[1])  # 初始化模型

In [6]:
# 定义loss和优化函数
criterion = nn.MSELoss()  # 定义损失（返回的损失求均值）
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)  # 定义优化算法

In [7]:
# 开始训练
x_train, y_train = torch.from_numpy(x), torch.from_numpy(y)

num_epochs = 500
for epoch in range(num_epochs):
    # forward
    out = model(x_train)
    loss = criterion(out, y_train)
    # backward
    optimizer.zero_grad()  # 梯度归零
    loss.backward()  # 梯度反向传播
    optimizer.step()  # 参数更新

    if (epoch+1) % 20 == 0:
        print(f'Epoch[{epoch+1}/{num_epochs}], loss: {loss.item():.6f}')

Epoch[20/500], loss: 1.070045
Epoch[40/500], loss: 0.798322
Epoch[60/500], loss: 0.600273
Epoch[80/500], loss: 0.439965
Epoch[100/500], loss: 0.324623
Epoch[120/500], loss: 0.261415
Epoch[140/500], loss: 0.221819
Epoch[160/500], loss: 0.195056
Epoch[180/500], loss: 0.175119
Epoch[200/500], loss: 0.160305
Epoch[220/500], loss: 0.148831
Epoch[240/500], loss: 0.139905
Epoch[260/500], loss: 0.132884
Epoch[280/500], loss: 0.127237
Epoch[300/500], loss: 0.122688
Epoch[320/500], loss: 0.118748
Epoch[340/500], loss: 0.115227
Epoch[360/500], loss: 0.112303
Epoch[380/500], loss: 0.109781
Epoch[400/500], loss: 0.107577
Epoch[420/500], loss: 0.105598
Epoch[440/500], loss: 0.103842
Epoch[460/500], loss: 0.102283
Epoch[480/500], loss: 0.100852
Epoch[500/500], loss: 0.099520


In [9]:
loss.item()

0.09951964765787125

In [10]:
# model.eval()
with torch.no_grad():
    predict = model(x_train)
predict = predict.data.numpy()

In [11]:
print(predict)

[[0.5588868  0.7004161  0.6881465  0.6089581 ]
 [0.57924163 0.67436874 0.38210595 0.46884045]
 [0.57407403 0.67948794 0.45658678 0.50252277]
 [0.575224   0.74354994 0.5803862  0.5775442 ]
 [0.55955523 0.6173402  0.5010814  0.50030094]
 [0.5755481  0.7008512  0.48447806 0.52179945]
 [0.5775826  0.6565745  0.36416942 0.45505407]
 [0.5667039  0.6846056  0.5581117  0.5477977 ]
 [0.6030781  0.9300318  0.6398135  0.6669194 ]
 [0.5275237  0.39913446 0.42465407 0.39276758]
 [0.52822566 0.44993082 0.52539474 0.45335868]
 [0.551838   0.5289761  0.40560848 0.4290949 ]
 [0.562738   0.6234915  0.4752394  0.49133083]
 [0.5181441  0.43875343 0.62513536 0.492285  ]
 [0.60125    0.9548234  0.71563834 0.7079189 ]
 [0.51631784 0.48640648 0.7501554  0.56220704]
 [0.5463866  0.6470934  0.7268518  0.6072786 ]
 [0.5237446  0.29261225 0.24172722 0.27785015]
 [0.5407553  0.37929535 0.21945472 0.29800546]
 [0.52998745 0.2283073  0.02661885 0.16360354]
 [0.5360115  0.49261573 0.52168036 0.46639284]
 [0.60293084 