# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.4'

## Sorting

Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
out = np.sort(x, axis=1)
x.sort(axis=1)
assert(np.array_equal(out, x))
print(out)

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
print(np.lexsort((first_names, surnames)))  # 类似sort_values(a, b),a相同时看b

[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])
out = np.argsort(x, axis=1)
print(out)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [7]:
x = np.random.permutation(10)
print("x =", x)
print("\nCheck the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5\n") 
out = np.partition(x, 5)  # 按照元素5来划分数组，使得左侧小于5,右侧大于5.
x.partition(5) # in-place equivalent
assert np.array_equal(x, out)
print(out)


x = [0 8 7 3 1 6 9 4 5 2]

Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5

[0 1 2 3 4 5 6 9 8 7]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [9]:
x = np.random.permutation(10)
print("x =", x)
partitioned = np.partition(x, 3)
print(partitioned)
indices = np.argpartition(x, 3)
print("partitioned =", partitioned)
print("indices =", partitioned)
assert np.array_equiv(x[indices], partitioned)

x = [7 5 9 4 6 3 8 1 2 0]
[0 1 2 3 4 5 6 8 9 7]
partitioned = [0 1 2 3 4 5 6 8 9 7]
indices = [0 1 2 3 4 5 6 8 9 7]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [10]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)
print("maximum values =", np.max(x, 1))
print("max indices =", np.argmax(x, 1))
print("minimum values =", np.min(x, 1))
print("min indices =", np.argmin(x, 1))

x = [[2 5 1 8 7]
 [3 4 6 9 0]]
maximum values = [8 9]
max indices = [3 3]
minimum values = [1 0]
min indices = [2 4]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [11]:
x = np.array([[np.nan, 4], [3, 2]])
print(np.max(x, 1))
print("maximum values ignoring NaNs =", np.nanmax(x, 1))
print("max indices =", np.nanargmax(x, 1))
print("minimum values ignoring NaNs =", np.nanmin(x, 1))
print("min indices =", np.nanargmin(x, 1))

[nan  3.]
maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [113]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print("Values bigger than 2 =", x[x>2])
print("Their indices are ", np.nonzero(x > 2))
assert np.array_equiv(x[x>2], x[np.nonzero(x > 2)])
assert np.array_equiv(x[x>2], np.extract(x > 2, x))

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [12]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print(np.flatnonzero(x>2))
assert np.array_equiv(np.flatnonzero(x), x.ravel().nonzero())

[2 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [13]:
x = np.arange(-5, 4).reshape(3, 3)
print(np.where(x <0, 0, x))

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [14]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3])

## Counting

Q12. Get the number of nonzero elements in x.

In [15]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
print(np.count_nonzero(x))
assert np.count_nonzero(x) == len(x[x!=0])

5
